# Generated by Django 3.1.1 on 2020-12-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.URLField(default='https://www.meme-arsenal.com/memes/8b6f5f94a53dbc3c8240347693830120.jpg'),
        ),
    ]
