# Generated by Django 3.1.1 on 2020-12-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201229_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='background_image',
            field=models.URLField(default='https://wallpapercave.com/wp/wp3589893.jpg'),
        ),
    ]
